### ISSUE TITLE
Fails when screensharing

### ISSUE THREAD

**Issue by EthanG45** [x74353/KeyJerk-Reactions#3]
macOS nests the reactions menu under a different header when you are screen sharing. This prevents KeyJerk from working.

_the usual menu_

![image](https://github.com/user-attachments/assets/9c069540-dbf7-4a01-8aaf-9d757be09704)

_when screen sharing_

![image](https://github.com/user-attachments/assets/6b8578c5-1d12-4fba-83fc-ba8d065af0a8)

This can get even more complicated when multiple apps are requesting camera control because a tab bar is presented at the top.

![image](https://github.com/user-attachments/assets/41c4c894-4ee4-4a8b-9317-f2d7c5b439be)

**Comment by x74353** [comment]
@EthanG45, thanks for reporting this issue. I've just uploaded a dmg for KeyJerk Reactions 2.0, which should hopefully fix this issue. Note that when multiple apps are accessing your Mac's camera, you won't have the ability to choose which app to apply the Reaction in. KeyJerk Reactions will typically apply the Reaction in first app in the "tab bar."

On some Macs, where an audio or video system extension is installed, such as ARK/ACE from Rouge Amoeba, KeyJerk Reactions may be unable to apply a Reaction due to the system extension being the first item in the "tab bar."

**Comment by EthanG45** [comment]
@x74353 thank you so much! I just tested and can confirm it works. I notice the app is setup differently now in that there is no AppleScript version anymore. However since KeyJerk Reactions itself supports AppleScript, it sounds like we can automate this in other apps like Raycast. I'll have to look at making an extension that links the two. Thanks!
