### ISSUE TITLE
Allow hiding the menu bar icon

### ISSUE THREAD

**Issue by EthanG45** [x74353/KeyJerk-Reactions#4]
Based on my reading of how KeyJerk Reactions 2.0 works, you can use AppleScript to automate reactions with it. I'm assuming at this point the menubar icon wouldn't be necessary for AppleScript usage? Can we get an option to hide the menubar icon?

**Comment by x74353** [comment]
@EthanG45 I've implemented a setting for this. When KeyJerk Reactions first launches, its menu bar icon will be present for ~30 seconds, allowing you to access Settings and re-enable the menu bar icon. Otherwise, after 30 seconds, it will remove itself from the menu bar. Will upload the new dmg to GitHub tomorrow (probably) after wrapping up some other work.
![ScreenShot 2024-11-04 at 22 58 35](https://github.com/user-attachments/assets/e4257522-a243-47d3-a312-356d5f3ffc95)

**Comment by x74353** [comment]
The 2.0.1 release has been added to the repo. This version adds the show/hide in menu bar setting.
