### ISSUE TITLE
Shortcuts support

### ISSUE THREAD

**Issue by EthanG45** [x74353/KeyJerk-Reactions#5]
Is it possible to add native Shortcuts support to the 2.0 version of the app? I know we could use the AppleScript option within Shortcuts, but this isn't the preferred way of writing a Mac native modern shortcut.

**Comment by x74353** [comment]
@EthanG45 I attempted to add Shortcuts support, but ran into quite a few issues. I was eventually able to get the intents to appear in the Shortcuts app, but attempting to run them throws an error. I will keep trying on this, but honestly,  I'm at a loss as to what the issue is.
![ScreenShot 2024-11-04 at 08 13 20](https://github.com/user-attachments/assets/b67d5b54-d105-4eab-a6e8-99e2d7d4ce3b)

**Comment by x74353** [comment]
@EthanG45 I was more successful today 🎉
![ScreenShot 2024-11-04 at 22 27 07](https://github.com/user-attachments/assets/c19c3b22-4678-4736-af9d-be79feeaed84)

**Comment by x74353** [comment]
The 2.0.1 release has been added to the repo. This version supports Shortcuts.
